### PR TITLE
Screen reader +++

### PR DESCRIPTION
**Pull request by ffoodd**
I first resetted my fork to match the original repo, so this PRs only changes the screenReader add-on.

To be accurate:
- first things first, any tag may have `aria-hidden` without being in `display: none`: that's our case here, since the visible text (in `<span>`) should not be read aloud by screen readers;
- instead, we'll "copy" its text **inside** the anchor (which allows it to expose an accessible name to assistive technologies such as screen readers) and wrap it inside another `<span>` with the `.mm-sronly` class: it'll be read aloud by screen readers as an anchor link, but won't trouble the visual appearance of the existing menu.

This way, the DOM and look doesn't break (nothing to change in the core's CSS nor JS), anchors are now fully accessible thanks to their accessible name, and everyone got the exactly same text for anchors.

I hope I'm clear enough, please ask me anything if not.

As a complement, please take a look at [WCAG criterion about accessible names, roles and values](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html). This might be clearer than I am.

I also improved the `.mm-sronly` class with [Yahoo!'s way](https://developer.yahoo.com/blogs/ydn/clip-hidden-content-better-accessibility-53456.html), and a small fix from me. It ensures that visually hidden things won't ever appear, even in RTL mode or when `clip` would be unsupported.

I hope it helped, and many thanks for reviewing this!

### CODE REVIEW

**Comment by ffoodd** [comment]
@FrDH I just saw I didn't push compiled files, should I?

**Comment by FrDH** [comment]
Looks great, I'll merge and push a new version shortly.
Thanks.

**Comment by ffoodd** [comment]
I just improved this a bit:
* `[aria-haspopup]` needs `[aria-owns]` to match the [WAI-ARIA pattern](https://www.w3.org/TR/wai-aria/states_and_properties#aria-haspopup);
* text value better match context instead of arbitrary strings script defined.

I think it's better this way. I'd like to hear your opinion, I made my best to stick to your coding conventions.

**Comment by rudzboy** [comment]
+1

**Comment by FrDH** [comment]
There now are some conflicts with the minified js files so I can't merge this PR. Could you remove them from the PR?

**Comment by ffoodd** [comment]
I'll do as soon as I get the time. I also need to test it with the advanced demo page to be sure it works as intended with advanced configuration and addons.

**Comment by ffoodd** [comment]
There's no conflict anymore.

I made a small improvement involving navbar prev/next to get `aria-owns` but I ensure to check if present.

I can't work more on this but it would need, obviously. Things that are still not quite good for screen reader users:
* searchfield should have a label: this involves add an `id` to the field, and a `<label>`  with a `for` attribute getting field's id. The label may have the `sr-only` class to visually hide it, but that could be optionnal.
* prev links shouldn't have `aria-hidden` set to true, their neighbour `title` should.

There's probably more to do but I can't work on this anymore, sorry :/

I think this PR is quite good even if it could be better, I hope it'll help.

**Pull request merged**
