### PR TITLE
Fix links labels

### PR DESCRIPTION
**Pull request by ffoodd**
Here it is. To label anchors in mmenu, I only take the span text content and paste it to an `aria-label` attribute.

Now a list of links (as exposed by some ATs) won't have empty links because of mmenu.

### CODE REVIEW

**Comment by ffoodd** [comment]
To be more accurate, the way you add a text in your screenReader add-on doesn't comply since you add the same text to every anchors. It's not possible to distinguish an anchor from another, and that's annoying.

As a personal point, I don't understand why keyboardNavigation and screenReader add-ons are add-ons. These features should be included for everyone. 

This is about about accessibility, not about features.

**Comment by FrDH** [comment]
Thank you for the feedback, I'll look into the "not being able to distinguish an anchor from another".

The keyboardNavigation and screenReader add-ons are not included in the core because they add specific behavior for screen readers and desktops. If the plugin is used on mobile devices only, these add-ons add an lot of extra code.

Therefor, if you will, please implement the changes to the screenReader add-on.

**Comment by ffoodd** [comment]
Mobile devices also have screen readers.. VoiceOver on iOS, TalkBack on Android, Narrator on Windows Phone... And blind users also use their smartphones.

And labelling links and anchors is needed for everyone and everywhere. In fact you shouldn't need extra code for this, the core code should just wrap the link around the initial span. This would need some CSS refactoring though, but you souldn't need extra JS. 

I understand your point and will try to make the PR on the addon, but this is a really bad point for this plugin :/

**Comment by FrDH** [comment]
You have a valid point about mobile screen readers. However, I strongly feel the need extract specific functionality from the core functionality. This keeps things clear and maintainable.

To put things in perspective: the entire off-canvas behavior is provided by an add-on.

I guess it's a good idea to include the accessibility add-ons into the default .js and .css files (just like the offCanvas and scrollBugFix add-ons). I'll put it on the TODO list, for now, you can use either the ".all" files or include the add-on files seporately.

Please appreciate the large amount of time I've spent on this plugin, it's documentation and support (it dates back to 2012). Comments like "pretty shitty" make me want to close a PR without any further reading.

**Comment by ffoodd** [comment]
There's also "I respect the author". I do appreciate the entire work, I wouldn't be opening pull request if I didn't :)

But we're talking about a navigation plugin, and the fact that I **must** use add-ons **to be able to navigate** in it is heresy. I also really think it could be much more simpler if those features were in your plugin's core, and simpler for you to maintain and work with.

I'm trying to fix  the screenReader add-on to submit it to you, I think you can close those two PRs since it'll be easier to merge the add-on PR.

Thanks a lot for responding!

**Comment by FrDH** [comment]
Closed as requested :)

p.s.
Since the screenReader add-on has its own version of `.sr-only` (`.mm-sronly` is actually an exact copy of the CSS), I don't think it is necessary to add a seporate Bootstrap version.

**Pull request closed without merging**
