### PR TITLE
Keyboard nav+++

### PR DESCRIPTION
**Pull request by ffoodd**
- tabstart and tabend no longer require extra markup (first focusable element is tabstart, last focusable element in each list are tabend);
- new trigger option to store element opening mmenu, which helps to give focus to tabstart and to get focus back from tabend;
- tabend tab now focus the trigger element when tabbing forward;
- titles are removed from tabindex, since back links are the same: only tab once is faster (but mouse can still click the entire area).

I hope it's clearer than screenReader PR, I did my best to stick to your coding style.

### CODE REVIEW

**Comment by FrDH** [comment]
Thanks, I had a look and think I found an issue with removing the "tabend" element, if you use the searchfield add-on, the last focusable list item might be hidden. Could you please check?

**Comment by FrDH** [comment]
...same goes for the "tabstart" element.

**Comment by ffoodd** [comment]
I'll check ASAP, thanks for reviewing :)

**Comment by FrDH** [comment]
Also, the tabstart element was used to prevent the first focusable element (list item) from receiving focus by default. If the `keyboardNavigation.enable` option was not set to `"default"`, the first focusable element should only receive focus after pressing tab for the first time.

**Comment by rudzboy** [comment]
+1

**Comment by FrDH** [comment]
@ffoodd any word on the questions about this PR?

**Comment by ffoodd** [comment]
I didn't have time to work on this, but I tested it and I confirm your guess: there's some strange things happening! I'm considering a few solutions.
I'll work with your advanced demo as a basic.

As far as I can see, there's some trouble with bottom/top navbars, since tab order doesn't reflect visual order (which can be quite surprising).

Also some focus styles should be enforced to make it more visible.

**Comment by ffoodd** [comment]
I can't work on this anymore, but I think this PR isn't good enough to be merged: there's surprising things happening with some other add-ons, and tabbing back is way too complicated for me to improve in my PR.

Since your current version is pretty good (yet improvable) I suggest you close my PR and try to improve current version when you'll get interest in it.

Tabbing and tabbing back should be easy and logical, that's the spirit.

I'm very sorry I couldn't help more with this :( But thanks a lot for your attention and time!

**Comment by FrDH** [comment]
Closed as requested.
I adopted adding `tabindex="-1"` to the ".mm-title". Although its behavior is configurable, its function is always a duplicate.

**Pull request closed without merging**
