### PR TITLE
Prevent children from bubbling up the transitionend event

### PR DESCRIPTION
**Pull request by smachi**
I want to resolve issues #604 and #599

### CODE REVIEW

**Comment by FrDH** [comment]
In `$(e.target).is(glbl.$page).first()` what is `e`?
I cant find any reference to it, so if it is `undefined`, so will `e.target` be. If so, the if-statement will always evaluate to `false`.

**Comment by FrDH** [comment]
I see the issue with events bubbling up from childnodes, but you should not be testing for `glbl.$page.first()` because the "page" isn't the only HTML element using the `__transitionend` method.

This should work, could you test is it fixes your issue?
````js
__transitionend: function( $e, fn, duration )
{
    var _ended = false,
        _fn = function( e )
        {
            if ( !_ended && $(e.target).is( $e )
            {
                _ended = true;
            }
        };

    $e.one( _e.transitionend, _fn );
    $e.one( _e.webkitTransitionEnd, _fn );

    setTimeout( _fn, duration * 1.1 );
}
````

**Comment by smachi** [comment]
Sure, I'll try it and will let you know asap. Thanks.

**Comment by smachi** [comment]
As I thought, the code Is not working without changing the `$.one` handlers to `$.on`.
Anyway, I've updated my previous patch to use `$e` instead of `glbl.$page.first()` to allow other elements to use the `__transitionend` method as you suggested.

Tested and working for me.

**Pull request merged**
